### ISSUE TITLE
Web page working in Zotero but error with Zoterobib? 

### ISSUE THREAD

**Issue by symac** [zotero/bib-web#239]
Hello,
I was trying to use ZoteroBib (using the official install at https://zbib.org/) with the discovery tool of my library that we are currenlty setting up but it seems there is an issue, which does not appear when using "classic" Zotero. 

If you try to add citation from [this page](https://pudb-primosb.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=TN_medline29748161&context=PC&vid=33PUDB_UBM_VU1&lang=fr_FR&search_scope=default_scope&adaptor=primo_central_multiple_fe&tab=default_tab&query=any,contains,wikipedia&sortby=rank&offset=0) you will get a red banner at the top of the website saying : "An error occurred while citing this source."

Visiting this page with Zotero installed on my computer I am able to save the item to my local library, so it seems there is an issue in the way zoterobib handles this URL.

**Comment by dstillman** [comment]
Basically this: https://zbib.org/faq#i-m-getting-an-error-trying-to-add-an-item-what-do-i-do

Zotero makes external, unauthenticated requests to sites, so if the site A) isn't available from the outside and/or B) doesn't include info in the URL that can identify the item being viewed, ZoteroBib generally can't save it. The one exception to A is that, if the site is gated but we can recognize a proxy in the URL, we can strip the proxy part and make a public request for the item, which often works.

In this case the server doesn't appear to even be accessible to external IP addresses, and the URL doesn't contain any information that clearly identifies a proxy. If 29748161 is indeed the PMID we could conceivably look for that pattern.

The Zotero Connector is able to look at the page in your browser, so access issues like that don't affect it.

(We can make that FAQ answer more explicit, since you're not the first person to ask.)

**Comment by symac** [comment]
Thanks @dstillman , I am so much into configuration at this time and spending so much time on this website that I had even forgotten that we had declared IP with the provider and that it was not opened yet to the public. 
Not sure if it is an issue with the FAQ, rather me being extremely focused on this new platform and not thinking about this IP config!
